### ISSUE TITLE
如何知道我们需要的几个类的类名呢？  我看你是直接写死的。难道用猜？

### ISSUE THREAD

**Issue by guoguoup** [Chion82/WeChatMomentStat-Android#13]
比如这个类名com.tencent.mm.protocal.b.atp 就是代表 朋友圈详细内容
比如这个
朋友圈评论和点赞数据
类名: com.tencent.mm.protocal.b.aqi
[方法]添加属性（可作为hook的方法）: protected final int a(int paramInt, object... objectArray)
[方法]从BLOB数据导入：public a am(byte[])
[属性]用户ID：String iYA
[属性]用户昵称：String jyd
[属性]时间戳：long fpL
[属性]评论列表：LinkedList<com.tencent.mm.protocal.b.apz> jJX
[属性]点赞列表：LinkedList<com.tencent.mm.protocal.b.apz> jJU

这些我如何知道，尤其是变量。我怎么知道这个混淆后的  fql就是代表时间戳啊？

**Comment by Chion82** [comment]
这些都是通过逆向微信apk以及借助Xposed调试得出来的。当然，逆向过程中是需要工程经验和不断猜测的，然后再使用Xposed验证我们的猜想。具体的逆向过程可以参考我写的这篇博文：[用Xposed框架抓取微信朋友圈数据](https://blog.chionlab.moe/2016/01/22/use-xposed-to-crawl-wechat-moments/) 这篇博文是早期编写的，当时我的逆向成果仅限从安卓UI组件取数据。
