### ISSUE TITLE
从加密数据库获取数据？

### ISSUE THREAD

**Issue by ruanqin0706** [Chion82/WeChatMomentStat-Android#18]
SnsMicroMsg.db是一个加密的数据库，但是我看到你在类SnsReader的方法queryDatabase()中，直接就调用了SQLiteDatabase.openDatabase(dbPath, null, 0);  并没抛出类似SQLiteCantOpenDatabaseException:这样的异常！！！ 难道是我对数据库的理解错误？

**Comment by Chion82** [comment]
数据库本身不是加密的，使用通常的sqlite查看工具都可以打开。加密的是部分字段
