### ISSUE TITLE
查询微信缓存失败,请允许root权限后重试.

### ISSUE THREAD

**Issue by scriptExplorer** [Chion82/WeChatMomentStat-Android#20]
确定已经给了root权限,不知道为什么总是这样提示?

设备:小米
系统: Android5.0.2 MIUI7.0.8.0
微信:6.3.28

**Comment by kongwu-** [comment]
确定已经给了root权限,不知道为什么总是这样提示?

设备:华为荣耀v8
系统: Android6.0.1 emui4.1 b170
微信:6.3.30

**Comment by Chion82** [comment]
请大家在提交issue时请带上logcat的错误信息。

**Comment by qinst64** [comment]
提示没有root权限的朋友查看一下系统设置是不是为软件允许了storage权限？

显然WeChatMomentStat需要使用sdcard，但是软件使用过程没有弹出请求框。
可能是作者@Chion82忘了这部分代码，或者使用android lollipop以下的版本？

**Comment by kongwu-** [comment]
已解决，就是存储权限的问题，手动给个权限就可以了

**Comment by phu113** [comment]
@kongwu- 
请问如何手动给存储权限？需要sc card吗？谢谢！
