### ISSUE TITLE
【严重】拉取朋友圈一直显示“正在加载”，如何解决这个问题？

### ISSUE THREAD

**Issue by absir1949** [Chion82/WeChatMomentStat-Android#21]
网速没有问题。是不是微信限制？

**Comment by Chion82** [comment]
请尝试清空微信应用数据后再试

**Comment by absir1949** [comment]
清空微信数据是类似于去 安卓设置-应用-微信-清除数据吗？
这样子微信所有数据都会清理掉额，上面的情况你有没有遇到过？

**Comment by absir1949** [comment]
AccessibilityService 没有拖动的功能,因此我们在模拟器里面只能去实现滑动朋友圈，不能实现拖动，而如果不拖动，那么有很高的概率会显示正在加载，一直不会有新内容，

按住屏幕，向上拖，朋友圈这样会弹一下，会把后面的内容加载处理，而一直滑动，只能显示当前列表的，有时当前列表显示完了，最下面就显示“正在加载”..滑动不会加载出来，只有拖动才能加载出来

关于模拟器用AccessibilityService去滑动朋友圈而很高概率显示正在加载，请问一下大神 @Chion82 有思路解决这个问题吗？

**Comment by Chion82** [comment]
这个是微信的问题，和本项目没有必然关系。怎么确定不是网络的问题呢？换个ISP试试呢？
