### ISSUE TITLE
查询微信缓存失败,请允许root权限后重试.

### ISSUE THREAD

**Issue by forrest2015** [Chion82/WeChatMomentStat-Android#25]
很奇怪，已经用360一键root了手机，并且也允许可以root运行。 但是一直弹出这个提示。 
权限管理 那边也允许读取写入。

小米note
Android 4.4.4

**Comment by Chion82** [comment]
请贴logcat记录

**Comment by forrest2015** [comment]
02-09 10:21:28.911 D/PowerCalculator( 1741): computePackageForegroundLocked, packageName: moe.chionlab.wechatmomentstat oldPackageForeground: false packageForeground: false

02-09 10:21:30.641 D/PowerCalculator( 1741): computePackageForegroundLocked, packageName: moe.chionlab.wechatmomentstat oldPackageForeground: false packageForeground: false

02-09 10:21:33.251 D/PowerCalculator( 1741): computePackageForegroundLocked, packageName: moe.chionlab.wechatmomentstat oldPackageForeground: false packageForeground: false

02-09 10:21:58.991 D/PowerCalculator( 1741): computePackageForegroundLocked, packageName: moe.chionlab.wechatmomentstat oldPackageForeground: false packageForeground: false

02-09 10:22:02.101 D/PowerCalculator( 1741): computePackageForegroundLocked, packageName: moe.chionlab.wechatmomentstat oldPackageForeground: false packageForeground: false

02-09 10:22:06.681 D/PowerCalculator( 1741): computePackageForegroundLocked, packageName: moe.chionlab.wechatmomentstat oldPackageForeground: false packageForeground: false

02-09 10:24:01.265 D/PowerCalculator( 1741): computePackageForegroundLocked, packageName: moe.chionlab.wechatmomentstat oldPackageForeground: false packageForeground: false

02-09 10:24:04.905 D/PowerCalculator( 1741): computePackageForegroundLocked, packageName: moe.chionlab.wechatmomentstat oldPackageForeground: false packageForeground: false

02-09 10:24:05.355 I/ActivityManager( 1115): Killing 11650:moe.chionlab.wechatmomentstat/u0a138 (adj 14): cached #5

02-09 10:24:05.405 I/WindowState( 1115): WIN DEATH: Window{4369eaf8 u0 moe.chionlab.wechatmomentstat/moe.chionlab.wechatmomentstat.gui.MainActivity}
02-09 10:24:05.435 D/ProcessObserver( 1741): onForegroundActivitiesChanged, pid: 11893 uid: 10041 foregroundActivities: false

02-09 10:24:09.545 I/ActivityManager( 1115): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=moe.chionlab.wechatmomentstat/.gui.MainActivity bnds=[845,604][1013,772]} from pid 1621

02-09 10:24:09.575 I/ActivityManager( 1115): Start proc moe.chionlab.wechatmomentstat for activity moe.chionlab.wechatmomentstat/.gui.MainActivity: pid=14425 uid=10138 gids={50138, 1028, 1015, 3003}
02-09 10:24:09.595 D/PowerKeeperEventLogManager( 1741): notifyForegroundCompomentChanged ComponentInfo{moe.chionlab.wechatmomentstat/moe.chionlab.wechatmomentstat.gui.MainActivity}
02-09 10:24:09.595 D/WhetstoneService( 1566): set foreground process size 1 pid:14425pacakgeName:moe.chionlab.wechatmomentstat
02-09 10:24:09.595 W/WhetstoneService( 1566): {WhetstonePackageInfo#PacakgeName:moe.chionlab.wechatmomentstatFlag:1024 [,SOFT_RESET] Type:0[] }not support ZRAM
02-09 10:24:09.605 D/PowerKeeperStateMachine( 1741): eventMessage id:100 name:foreground
02-09 10:24:09.605 D/PowerCalculator( 1741): computePackageForeground: packageName = moe.chionlab.wechatmomentstat

02-09 10:24:09.605 D/PowerCalculator( 1741): computePackageForegroundLocked, packageName: moe.chionlab.wechatmomentstat oldPackageForeground: false packageForeground: true
02-09 10:24:09.605 D/PowerCalculator( 1741): updatePowerForPackage: packageName: moe.chionlab.wechatmomentstat packageForeground: true

02-09 10:24:09.655 D/NetworkController( 1741): send broadcast android.net.conn.CONNECTIVITY_CHANGE to moe.chionlab.wechatmomentstat

02-09 10:24:10.025 I/ActivityManager( 1115): Displayed moe.chionlab.wechatmomentstat/.gui.MainActivity: +470ms

02-09 10:24:10.125 I/Timeline( 1115): Timeline: Activity_windows_visible id: ActivityRecord{42ec0740 u0 moe.chionlab.wechatmomentstat/.gui.MainActivity t115} time:33548880

02-09 10:24:12.025 D/wechatmomentstat(14425): Querying Sns database.
02-09 10:24:12.025 E/wechatmomentstat(14425): DB file not found
02-09 10:24:12.045 W/Toast   (14425): From moe.chionlab.wechatmomentstat, go ahead.
02-09 10:24:12.055 E/wechatmomentstat(14425): exception
02-09 10:24:12.055 E/wechatmomentstat(14425): java.lang.Exception: DB file not found
02-09 10:24:12.055 E/wechatmomentstat(14425): 	at moe.chionlab.wechatmomentstat.SnsReader.queryDatabase(SnsReader.java:45)
02-09 10:24:12.055 E/wechatmomentstat(14425): 	at moe.chionlab.wechatmomentstat.SnsReader.run(SnsReader.java:33)
02-09 10:24:12.055 E/wechatmomentstat(14425): 	at moe.chionlab.wechatmomentstat.gui.MainActivity$RunningTask.doInBackground(MainActivity.java:62)
02-09 10:24:12.055 E/wechatmomentstat(14425): 	at moe.chionlab.wechatmomentstat.gui.MainActivity$RunningTask.doInBackground(MainActivity.java:53)
02-09 10:24:12.055 E/wechatmomentstat(14425): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
02-09 10:24:12.055 E/wechatmomentstat(14425): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-09 10:24:12.055 E/wechatmomentstat(14425): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
02-09 10:24:12.055 E/wechatmomentstat(14425): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
02-09 10:24:12.055 E/wechatmomentstat(14425): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
02-09 10:24:12.055 E/wechatmomentstat(14425): 	at java.lang.Thread.run(Thread.java:841)

02-09 10:24:13.255 D/PowerCalculator( 1741): computePackageForegroundLocked, packageName: moe.chionlab.wechatmomentstat oldPackageForeground: true packageForeground: false
02-09 10:24:13.255 D/PowerCalculator( 1741): updatePowerForPackage: packageName: moe.chionlab.wechatmomentstat packageForeground: false
02-09 10:24:13.255 D/PowerCalculator( 1741): countPower: packageName = moe.chionlab.wechatmomentstat lastPower = 308033 currentPower = 308316

02-09 10:24:14.195 D/PowerCalculator( 1741): computePackageForegroundLocked, packageName: moe.chionlab.wechatmomentstat oldPackageForeground: false packageForeground: false

02-09 10:24:20.696 D/PowerCalculator( 1741): computePackageForegroundLocked, packageName: moe.chionlab.wechatmomentstat oldPackageForeground: false packageForeground: false

02-09 10:24:22.826 D/PowerCalculator( 1741): computePackageForegroundLocked, packageName: moe.chionlab.wechatmomentstat oldPackageForeground: false packageForeground: false

02-09 10:24:25.276 D/PowerCalculator( 1741): computePackageForegroundLocked, packageName: moe.chionlab.wechatmomentstat oldPackageForeground: false packageForeground: false

02-09 10:25:27.866 D/PowerCalculator( 1741): key = moe.chionlab.wechatmomentstat value = 5505 time = 91305

**Comment by forrest2015** [comment]
不晓得是不是这些log，菜鸟一只，麻烦你了。 谢谢

**Comment by Chion82** [comment]
参考#3
> 请检查在外部存储的WeChatMomentStat目录中是否有SnsMicroMsg.db这个文件。如果没有这个文件，说明微信数据库文件拷贝失败，请尝试手动将/data/data/com.tencent.mm/MicroMsg/XXX/SnsMicroMsg.db（其中XXX为一串hash值，每台设备上都不一样）复制到/sdcard/WeChatMomentStat/SnsMicroMsg.db

**Comment by forrest2015** [comment]
@Chion82  十分感谢， 但是还是出现“查询微信缓存失败,请允许root权限后重试”。
WeChatMomentStat目录下 有
all_sns.json  --- 0 kb
SnsMicroMsg.db
SnsMicroMsg.db-journal
wechat.apk

**Comment by forrest2015** [comment]
02-10 11:29:56.436 I/dalvikvm(25497):   at moe.chionlab.wechatmomentstat.Task.saveToJSONFile(Task.java:229)
02-10 11:29:56.436 I/dalvikvm(25497):   at moe.chionlab.wechatmomentstat.SnsReader.run(SnsReader.java:34)
02-10 11:29:56.436 I/dalvikvm(25497):   at moe.chionlab.wechatmomentstat.gui.MainActivity$RunningTask.doInBackground(MainActivity.java:62)
02-10 11:29:56.436 I/dalvikvm(25497):   at moe.chionlab.wechatmomentstat.gui.MainActivity$RunningTask.doInBackground(MainActivity.java:53)
02-10 11:29:56.436 I/dalvikvm(25497):   at android.os.AsyncTask$2.call(AsyncTask.java:288)
02-10 11:29:56.436 I/dalvikvm(25497):   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-10 11:29:56.436 I/dalvikvm(25497):   at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
02-10 11:29:56.436 I/dalvikvm(25497):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
02-10 11:29:56.436 I/dalvikvm(25497):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
02-10 11:29:56.436 I/dalvikvm(25497):   at java.lang.Thread.run(Thread.java:841)
02-10 11:29:56.436 I/dalvikvm(25497): 
02-10 11:29:56.456 W/Toast   (25497): From moe.chionlab.wechatmomentstat, go ahead.
02-10 11:29:56.476 E/wechatmomentstat(25497): exception
02-10 11:29:56.476 E/wechatmomentstat(25497): java.lang.OutOfMemoryError
02-10 11:29:56.476 E/wechatmomentstat(25497): 	at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:94)
02-10 11:29:56.476 E/wechatmomentstat(25497): 	at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:132)
02-10 11:29:56.476 E/wechatmomentstat(25497): 	at java.lang.StringBuilder.append(StringBuilder.java:124)
02-10 11:29:56.476 E/wechatmomentstat(25497): 	at org.json.JSONStringer.string(JSONStringer.java:344)
02-10 11:29:56.476 E/wechatmomentstat(25497): 	at org.json.JSONStringer.value(JSONStringer.java:252)
02-10 11:29:56.476 E/wechatmomentstat(25497): 	at org.json.JSONObject.writeTo(JSONObject.java:672)
02-10 11:29:56.476 E/wechatmomentstat(25497): 	at org.json.JSONStringer.value(JSONStringer.java:237)
02-10 11:29:56.476 E/wechatmomentstat(25497): 	at org.json.JSONArray.writeTo(JSONArray.java:602)
02-10 11:29:56.476 E/wechatmomentstat(25497): 	at org.json.JSONArray.toString(JSONArray.java:574)
02-10 11:29:56.476 E/wechatmomentstat(25497): 	at moe.chionlab.wechatmomentstat.Task.saveToJSONFile(Task.java:229)
02-10 11:29:56.476 E/wechatmomentstat(25497): 	at moe.chionlab.wechatmomentstat.SnsReader.run(SnsReader.java:34)
02-10 11:29:56.476 E/wechatmomentstat(25497): 	at moe.chionlab.wechatmomentstat.gui.MainActivity$RunningTask.doInBackground(MainActivity.java:62)
02-10 11:29:56.476 E/wechatmomentstat(25497): 	at moe.chionlab.wechatmomentstat.gui.MainActivity$RunningTask.doInBackground(MainActivity.java:53)
02-10 11:29:56.476 E/wechatmomentstat(25497): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
02-10 11:29:56.476 E/wechatmomentstat(25497): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-10 11:29:56.476 E/wechatmomentstat(25497): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
02-10 11:29:56.476 E/wechatmomentstat(25497): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
02-10 11:29:56.476 E/wechatmomentstat(25497): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
02-10 11:29:56.476 E/wechatmomentstat(25497): 	at java.lang.Thread.run(Thread.java:841)

**Comment by forrest2015** [comment]
好像是 json 文件没有写入权限。

**Comment by Chion82** [comment]
允许外部存储读写权限试试呢？

**Comment by forrest2015** [comment]
哪里设置外部存储读写权限？
手机是 小米note， 已root，并且也解锁 system分区了。  试图去改all_sns.json的权限和用户组， 都是失败。。。 
也做了如下操作。

取得ROOT权限，安装RE管理器，找到位置：/system/etc/permissions/platform.xml长按之，选择在文本编辑器中打开。然后在下面这段代码中增加红色部分代码即可。

        <permission name="android.permission.WRITE_EXTERNAL_STORAGE" >             
        <group gid="sdcard_r" />                                               
        <group gid="sdcard_rw" />                                              
        <group gid="media_rw" />                                               
        </permission

**Comment by forrest2015** [comment]
@Chion82 all_sns.json  现在权限是 0660， 所有者和用户组 是 root/root

**Comment by Chion82** [comment]
看到有个Out of memory 异常，可能是缓存的朋友圈数据太多了？试试清空微信的保存数据，再登录微信只看几条朋友圈，然后再试试？

**Comment by Chion82** [comment]
记得重新手动复制db文件

**Comment by ouyangruoxue** [comment]
我在Windows里面用 genymotion模拟器里面跑的。在腾讯里面完全找不到db文件。。。

**Comment by ouyangruoxue** [comment]
![qq 20170210171416](https://cloud.githubusercontent.com/assets/7601301/22821238/36ad189e-efb5-11e6-8c4a-e42674e71589.png)
完全没有db 我是拿你release里面的那个微信apk直接装的

**Comment by ouyangruoxue** [comment]
![s70210-173244](https://cloud.githubusercontent.com/assets/7601301/22821659/0eb01ec0-efb7-11e6-8488-2aa720e9885d.jpg)
![s70210-173254](https://cloud.githubusercontent.com/assets/7601301/22821663/0edd8194-efb7-11e6-8818-011114683b13.jpg)
我在手机里面也找不到数据库文件。

**Comment by ouyangruoxue** [comment]
@Chion82 请问现在db文件路径换了吗？

**Comment by ouyangruoxue** [comment]
“/data/data/com.tencent.mm/”这个路径我在模拟器里面找
![qq 20170210175906](https://cloud.githubusercontent.com/assets/7601301/22822476/a3f53daa-efba-11e6-89ef-0ccf4f6fa0c5.png)
不到。。我已经给应用超级用户权限了

**Comment by ouyangruoxue** [comment]
android.database.sqlite.SQLiteException: no such table: snsExtInfo3 (code 1): , while compiling: SELECT userName FROM snsExtInfo3 WHERE ROWID=? LIMIT 1  @Chion82

**Comment by ouyangruoxue** [comment]
表改了好像。只有2了
![qq 20170210184330](https://cloud.githubusercontent.com/assets/7601301/22823944/e4b030b0-efc0-11e6-8b73-1e38091907ff.png)

**Comment by ouyangruoxue** [comment]
表现在变成了snsExtInfo2了。

**Comment by Chion82** [comment]
@ouyangruoxue 微信升级到6.3.28，本程序释放的apk不是让用户安装的，是拿来做反射的

**Comment by forrest2015** [comment]
@Chion82 的确是缓存太多的原因， 清空后就可以了。 对了，Json文件里怎么查看 朋友圈的图片？

**Comment by forrest2015** [comment]
medialist 里面的图片是要怎么才能访问到？ 谢谢

**Comment by Chion82** [comment]
@forrest2015 #16 目前无解
