### ISSUE TITLE
导出失败，发现db文件中内容很少

### ISSUE THREAD

**Issue by zhang-minchao** [Chion82/WeChatMomentStat-Android#32]
安装的微信6.3.31
从GitHub上下载的软件是1.1

使用软件失败，无法导出数据。在data/data/com.tencent.mm/MircoMsg/**some hash**/这目录下发现了三个sqlite的db文件，发现.db-wal文件418k，.db文件才188k。
将.db文件拷到电脑上，用sqlite管理工具打开发现，content字段只存了很少的内容，不知道是什么原因导致导出失败。
![Uploading G~(E[L_NELYCC{}$9[E$M9A.png…]()

在网上查询发现.db-wal文件是类似缓存的，还未合并到db文件之中。

**Comment by zhmc** [comment]
-5902604468687728436	wxid_h9l8f1m3gz0g72	2	1495377970	20170521	0	1	10	0	0	0000012544139605021823180	"
12544139605021823180wxid_h9l8f1m3gz0g72"	"̡𑥐wxid_h9l8f1m3gz0g72
A张民超 �І�*"	
-5970808636862164784	wxid_h9l8f1m3gz0g72	2	1487247400	20170216	0	3	8	0	0	0000012475935436847386832	"
12475935436847386832wxid_h9l8f1m3gz0g72"	"С��ߥۑ�wxid_h9l8f1m3gz0g72
A张民超 ����*"	
-6352685327655104306	wxid_h9l8f1m3gz0g72	2	1441724151	20150908	0	1	8	0	0	0000012094058746054447310	"
12094058746054447310wxid_h9l8f1m3gz0g72"	"Ρ�ڣˮ��wxid_h9l8f1m3gz0g72	张民超 ����*"	
-6362148467569913610	wxid_h9l8f1m3gz0g72	2	1440596056	20150826	0	2	8	0	0	0000012084595606139638006	"
12084595606139638006wxid_h9l8f1m3gz0g72"	��̱���ڧwxid_h9l8f1m3gz0g72
2EZ4张民超 ؀��*	
-6371949552442208048	wxid_h9l8f1m3gz0g72	2	1439427676	20150813	0	2	8	0	0	0000012074794521267343568	"
12074794521267343568wxid_h9l8f1m3gz0g72"	С��Ŵ�ɧwxid_h9l8f1m3gz0g72
2EZ4张民超 �د�*	
-6378755512798736170	wxid_h9l8f1m3gz0g72	2	1438616342	20150803	0	2	8	0	0	0000012067988560910815446	"
12067988560910815446wxid_h9l8f1m3gz0g72"	"֡�������wxid_h9l8f1m3gz0g72	张民超 ����*"	
-6382850544865373960	wxid_h9l8f1m3gz0g72	2	1438128176	20150729	0	2	8	0	0	0000012063893528844177656	"
12063893528844177656wxid_h9l8f1m3gz0g72"	"������㵧wxid_h9l8f1m3gz0g72	张民超 ����*"	
-6813843415170018595	wxid_h9l8f1m3gz0g72	2	1386749822	20131211	0	3	8	0	0	0000011632900658539533021	"
11632900658539533021wxid_h9l8f1m3gz0g72"	"ݥ�������wxid_h9l8f1m3gz0g72	张民超 ����*"	
-6818378879687780999	wxid_h9l8f1m3gz0g72	2	1386209153	20131205	0	3	8	0	0	0000011628365194021770617	"
11628365194021770617wxid_h9l8f1m3gz0g72"	"���������wxid_h9l8f1m3gz0g72	张民超 ����*"	
-6859047928517290640	wxid_h9l8f1m3gz0g72	2	1381361025	20131010	0	1	8	0	0	0000011587696145192260976	"
11587696145192260976wxid_h9l8f1m3gz0g72"	"���������wxid_h9l8f1m3gz0g72	张民超 ��ג*"	
-5900467325039275956	pm943151504	2	1495632737	20170524	0	4	2	0	0	0000012546276748670275660	"
12546276748670275660pm943151504"	̠�ѭ�Վ�pm943151504江倩 ᖖ�*	
-5900798497725140740	wxid_pv9it79ze5ci22	2	1495593258	20170524	0	15	10	0	0	0000012545945575984410876	"
12545945575984410876wxid_pv9it79ze5ci22"	�἟�����wxid_pv9it79ze5ci22铁哥 ����*	
-5900812285704924916	wxid_8wx3iu9nzput22	2	1495591615	20170524	0	3	2	0	0	0000012545931788004626700	"
12545931788004626700wxid_8wx3iu9nzput22"	�����φ��wxid_8wx3iu9nzput22fallen angel �Փ�*	
-5900823399121284843	wxid_8wx3iu9nzput22	2	1495590290	20170524	0	3	2	0	0	0000012545920674588266773	"
12545920674588266773wxid_8wx3iu9nzput22"	���������wxid_8wx3iu9nzput22fallen angel �˓�*	
-5901434270790635244	wxid_pv9it79ze5ci22	2	1495517468	20170523	0	15	10	0	0	0000012545309802918916372	"
12545309802918916372wxid_pv9it79ze5ci22"	��ԁę���wxid_pv9it79ze5ci22铁哥 ����*	
-5901919600197226240	wxid_pv9it79ze5ci22	2	1495459613	20170522	0	15	10	0	0	0000012544824473512325376	"
12544824473512325376wxid_pv9it79ze5ci22"	��Њ�슌�wxid_pv9it79ze5ci22铁哥 �΋�*	
-5901933579627253485	wxid_pv9it79ze5ci22	2	1495457946	20170522	0	15	10	0	0	0000012544810494082298131	"
12544810494082298131wxid_pv9it79ze5ci22"	�����Շ��wxid_pv9it79ze5ci22铁哥 ����*	
-5903586053903216375	wxid_8wx3iu9nzput22	2	1495260956	20170520	0	3	2	0	0	0000012543158019806335241	"
12543158019806335241wxid_8wx3iu9nzput22"	���������wxid_8wx3iu9nzput22fallen angel ����*	
-5904502028213153522	wxid_8wx3iu9nzput22	2	1495151763	20170519	0	3	2	0	0	0000012542242045496398094	"
12542242045496398094wxid_8wx3iu9nzput22"	�����ֿ��wxid_8wx3iu9nzput22fallen angel ����*	
-5904805341666397937	wxid_pv9it79ze5ci22	2	1495115605	20170518	0	3	10	0	0	0000012541938732043153679	"
12541938732043153679wxid_pv9it79ze5ci22"	�┱�����wxid_pv9it79ze5ci22铁哥 ����*	
-5906267831133195995	wxid_pv9it79ze5ci22	2	1494941263	20170516	0	3	10	0	0	0000012540476242576355621	"
12540476242576355621wxid_pv9it79ze5ci22"	���Ǵ����wxid_pv9it79ze5ci22铁哥 ����*	
-5909969642088419063	wxid_pv9it79ze5ci22	2	1494499973	20170511	0	3	10	0	0	0000012536774431621132553	"
12536774431621132553wxid_pv9it79ze5ci22"	����Ľ���wxid_pv9it79ze5ci22铁哥 ����*	
-5910095347148115674	wxid_pv9it79ze5ci22	2	1494484988	20170511	0	3	10	0	0	0000012536648726561435942	"
12536648726561435942wxid_pv9it79ze5ci22"	�Ⱔ�����wxid_pv9it79ze5ci22铁哥 ����*	
-5910770321663184598	wxid_pv9it79ze5ci22	2	1494404524	20170510	0	15	10	0	0	0000012535973752046367018	"
12535973752046367018wxid_pv9it79ze5ci22"	����ض���wxid_pv9it79ze5ci22铁哥 ����*	
-5912360762296028891	wxid_pv9it79ze5ci22	2	1494214929	20170508	0	3	10	0	0	0000012534383311413522725	"
12534383311413522725wxid_pv9it79ze5ci22"	�⌛�����wxid_pv9it79ze5ci22铁哥 �ҿ�*	
-5912490733785501435	wxid_pv9it79ze5ci22	2	1494199435	20170508	0	15	10	0	0	0000012534253339924050181	"
12534253339924050181wxid_pv9it79ze5ci22"	���׍����wxid_pv9it79ze5ci22铁哥 �پ�*	
-5912841051141820146	wxid_pv9it79ze5ci22	2	1494157674	20170507	0	3	10	0	0	0000012533903022567731470	"
12533903022567731470wxid_pv9it79ze5ci22"	���������wxid_pv9it79ze5ci22铁哥 ꒼�*	
-5914690349910773478	wxid_pv9it79ze5ci22	2	1493937221	20170505	0	3	10	0	0	0000012532053723798778138	"
12532053723798778138wxid_pv9it79ze5ci22"	�⌉펳��wxid_pv9it79ze5ci22铁哥 �خ�*	
-5916552322754793187	wxid_pv9it79ze5ci22	2	1493715256	20170502	0	3	10	0	0	0000012530191750954758429	"
12530191750954758429wxid_pv9it79ze5ci22"	���٧����wxid_pv9it79ze5ci22铁哥 ����*	
-6871990004286679700	wxid_h9l8f1m3gz0g72	2	1379818209	20130922	0	1	8	0	0	0000011574754069422871916	"
11574754069422871916wxid_h9l8f1m3gz0g72"	"�������Рwxid_h9l8f1m3gz0g72	张民超 ����*"	
-5917374864893726469	wxid_pv9it79ze5ci22	2	1493617201	20170501	0	3	8	0	0	0000012529369208815825147	"
12529369208815825147wxid_pv9it79ze5ci22"	�Ἱ�����wxid_pv9it79ze5ci22铁哥 ����*	
-5917375934946660093	wxid_pv9it79ze5ci22	2	1493617074	20170501	0	3	8	0	0	0000012529368138762891523	"
12529368138762891523wxid_pv9it79ze5ci22"	�⼘�����wxid_pv9it79ze5ci22铁哥 ����*	
-5919484664621092567	wxid_pv9it79ze5ci22	2	1493365694	20170428	0	3	8	0	0	0000012527259409088459049	"
12527259409088459049wxid_pv9it79ze5ci22"	���������wxid_pv9it79ze5ci22铁哥 ����*	
-5920411233139543782	wxid_pv9it79ze5ci22	2	1493255238	20170427	0	3	8	0	0	0000012526332840570007834	"
12526332840570007834wxid_pv9it79ze5ci22"	��𣞫���wxid_pv9it79ze5ci22铁哥 ƈ��*	
-5920412058445598449	wxid_pv9it79ze5ci22	2	1493255140	20170427	0	3	8	0	0	0000012526332015263953167	"
12526332015263953167wxid_pv9it79ze5ci22"	���㛓���wxid_pv9it79ze5ci22铁哥 䇅�*	
-5921541975061679853	wxid_pv9it79ze5ci22	2	1493120443	20170425	0	3	8	0	0	0000012525202098647871763	"
12525202098647871763wxid_pv9it79ze5ci22"	�∯�����wxid_pv9it79ze5ci22铁哥 ����*	
-5922406069636288232	wxid_pv9it79ze5ci22	2	1493017435	20170424	0	3	8	0	0	0000012524338004073263384	"
12524338004073263384wxid_pv9it79ze5ci22"	��؝�����wxid_pv9it79ze5ci22铁哥 ����*	
-5922408664679042810	wxid_pv9it79ze5ci22	2	1493017126	20170424	0	3	8	0	0	0000012524335409030508806	"
12524335409030508806wxid_pv9it79ze5ci22"	���������wxid_pv9it79ze5ci22铁哥 ����*	
-5922981136082980586	wxid_pv9it79ze5ci22	2	1492948882	20170423	0	1	8	0	0	0000012523762937626571030	"
12523762937626571030wxid_pv9it79ze5ci22"	���㛁���wxid_pv9it79ze5ci22铁哥 ����*	
-5924109345854312192	wxid_pv9it79ze5ci22	2	1492814389	20170422	0	3	8	0	0	0000012522634727855239424	"
12522634727855239424wxid_pv9it79ze5ci22"	���������wxid_pv9it79ze5ci22铁哥 ����*	
-5925498491499564788	wxid_pv9it79ze5ci22	2	1492648790	20170420	0	3	8	0	0	0000012521245582209986828	"
12521245582209986828wxid_pv9it79ze5ci22"	�⸈�Й��wxid_pv9it79ze5ci22铁哥 ֆ��*	
-5926255909757505238	wxid_pv9it79ze5ci22	2	1492558498	20170419	0	15	8	0	0	0000012520488163952046378	"
12520488163952046378wxid_pv9it79ze5ci22"	���������wxid_pv9it79ze5ci22铁哥 ����*	
-5928166769851092722	wxid_pv9it79ze5ci22	2	1492330706	20170416	0	15	8	0	0	0000012518577303858458894	"
12518577303858458894wxid_pv9it79ze5ci22"	���δ��ݭwxid_pv9it79ze5ci22铁哥 ����*	
-5928392387525136126	wxid_pv9it79ze5ci22	2	1492303810	20170416	0	15	8	0	0	0000012518351686184415490	"
12518351686184415490wxid_pv9it79ze5ci22"	�⼣�чݭwxid_pv9it79ze5ci22铁哥 ����*	
-5930420940761648892	wxid_pv9it79ze5ci22	2	1492061988	20170413	0	3	8	0	0	0000012516323132947902724	"
12516323132947902724wxid_pv9it79ze5ci22"	���ʳ��٭wxid_pv9it79ze5ci22铁哥 ����*	
-5932463174481071871	wxid_pv9it79ze5ci22	2	1491818535	20170410	0	3	8	0	0	0000012514280899228479745	"
12514280899228479745wxid_pv9it79ze5ci22"	����ʅ�խwxid_pv9it79ze5ci22铁哥 ����*	
-5932818711283617528	wxid_pv9it79ze5ci22	2	1491776152	20170410	0	3	8	0	0	0000012513925362425934088	"
12513925362425934088wxid_pv9it79ze5ci22"	�☩���խwxid_pv9it79ze5ci22铁哥 ����*	
-5934159130817122006	wxid_pv9it79ze5ci22	2	1491616361	20170408	0	3	8	0	0	0000012512584942892429610	"
12512584942892429610wxid_pv9it79ze5ci22"	�ℸ���ҭwxid_pv9it79ze5ci22铁哥 鄡�*	
-5944734927478443758	wxid_pv9it79ze5ci22	2	1490355628	20170324	0	3	8	0	0	0000012502009146231107858	"
12502009146231107858wxid_pv9it79ze5ci22"	���������wxid_pv9it79ze5ci22铁哥 ����*	
-5946432538805456644	wxid_pv9it79ze5ci22	2	1490153257	20170322	0	3	8	0	0	0000012500311534904094972	"
12500311534904094972wxid_pv9it79ze5ci22"	�����ぽ�wxid_pv9it79ze5ci22铁哥 ����*	
-5957017167226654448	wxid_pv9it79ze5ci22	2	1488891471	20170307	0	3	8	0	0	0000012489726906482897168	"
12489726906482897168wxid_pv9it79ze5ci22"	�ⴔ�����wxid_pv9it79ze5ci22铁哥 ����*	
-5965032512024334072	wxid_pv9it79ze5ci22	2	1487935967	20170224	0	3	8	0	0	0000012481711561685217544	"
12481711561685217544wxid_pv9it79ze5ci22"	���������wxid_pv9it79ze5ci22铁哥 ߳��*	
-5979574670668975866	wxid_pv9it79ze5ci22	2	1486202407	20170204	0	2	8	0	0	0000012467169403040575750	"
12467169403040575750wxid_pv9it79ze5ci22"	����ʐ���wxid_pv9it79ze5ci22铁哥 ����*	
-6007149095573507810	wxid_pv9it79ze5ci22	2	1482915279	20161228	0	3	8	0	0	0000012439594978136043806	"
12439594978136043806wxid_pv9it79ze5ci22"	���옷�Ѭwxid_pv9it79ze5ci22铁哥 ����*	
-6017612386131824373	wxid_pv9it79ze5ci22	2	1481667958	20161214	0	3	8	0	0	0000012429131687577727243	"
12429131687577727243wxid_pv9it79ze5ci22"	������ɾ�wxid_pv9it79ze5ci22铁哥 ����*	
-6064986025178746601	wxid_pv9it79ze5ci22	2	1476020580	20161009	0	3	8	0	0	0000012381758048530805015	"
12381758048530805015wxid_pv9it79ze5ci22"	�⌌�����wxid_pv9it79ze5ci22铁哥 ����*	
-6080940601790222044	wxid_pv9it79ze5ci22	2	1474118646	20160917	0	3	8	0	0	0000012365803471919329572	"
12365803471919329572wxid_pv9it79ze5ci22"	����ڗ�Ϋwxid_pv9it79ze5ci22铁哥 ����*	
-6081672121868078844	wxid_pv9it79ze5ci22	2	1474031442	20160916	0	3	8	0	0	0000012365071951841472772	"
12365071951841472772wxid_pv9it79ze5ci22"	�������̫wxid_pv9it79ze5ci22铁哥 ����*	
-6083837639755812589	wxid_pv9it79ze5ci22	2	1473773292	20160913	0	3	8	0	0	0000012362906433953739027	"
12362906433953739027wxid_pv9it79ze5ci22"	��Й���ȫwxid_pv9it79ze5ci22铁哥 ��߾*	
-6084560437280755442	wxid_pv9it79ze5ci22	2	1473687128	20160912	0	3	8	0	0	0000012362183636428796174	"
12362183636428796174wxid_pv9it79ze5ci22"	����А�ǫwxid_pv9it79ze5ci22铁哥 ��ھ*	
-6084697216034131672	wxid_pv9it79ze5ci22	2	1473670823	20160912	0	3	8	0	0	0000012362046857675419944	"
12362046857675419944wxid_pv9it79ze5ci22"	����샴ǫwxid_pv9it79ze5ci22铁哥 ��پ*	
-6103601759991877347	wxid_pv9it79ze5ci22	2	1471417226	20160817	0	3	8	0	0	0000012343142313717674269	"
12343142313717674269wxid_pv9it79ze5ci22"	������饫wxid_pv9it79ze5ci22铁哥 ��н*	
-6104926751163928295	wxid_pv9it79ze5ci22	2	1471259274	20160815	0	3	8	0	0	0000012341817322545623321	"
12341817322545623321wxid_pv9it79ze5ci22"	����񮼣�wxid_pv9it79ze5ci22铁哥 ��ƽ*	
-6105952906339995371	wxid_pv9it79ze5ci22	2	1471136947	20160814	0	3	8	0	0	0000012340791167369556245	"
12340791167369556245wxid_pv9it79ze5ci22"	��ܒ��ӡ�wxid_pv9it79ze5ci22铁哥 ����*	
-6122574226310811389	wxid_pv9it79ze5ci22	2	1469155531	20160722	0	3	8	0	0	0000012324169847398740227	"
12324169847398740227wxid_pv9it79ze5ci22"	�⠎�叄�wxid_pv9it79ze5ci22铁哥 ˑƼ*	
-6122576088483221211	wxid_pv9it79ze5ci22	2	1469155309	20160722	0	3	8	0	0	0000012324167985226330405	"
12324167985226330405wxid_pv9it79ze5ci22"	����ǯ���wxid_pv9it79ze5ci22铁哥 ��Ƽ*	
-6158680503173959410	wxid_pv9it79ze5ci22	2	1464851328	20160602	0	3	8	0	0	0000012288063570535592206	"
12288063570535592206wxid_pv9it79ze5ci22"	��ę���êwxid_pv9it79ze5ci22铁哥 ����*	
-6165090716056604416	wxid_pv9it79ze5ci22	2	1464087171	20160524	0	3	8	0	0	0000012281653357652947200	"
12281653357652947200wxid_pv9it79ze5ci22"	�⌫��̸�wxid_pv9it79ze5ci22铁哥 �吺*	
-6170162627009957616	wxid_pv9it79ze5ci22	2	1463482552	20160517	0	3	8	0	0	0000012276581446699594000	"
12276581446699594000wxid_pv9it79ze5ci22"	���Ձ�˯�wxid_pv9it79ze5ci22铁哥 ����*	
-6178044356983049978	wxid_pv9it79ze5ci22	2	1462542976	20160506	0	3	8	0	0	0000012268699716726501638	"
12268699716726501638wxid_pv9it79ze5ci22"	�⬻��ˡ�wxid_pv9it79ze5ci22铁哥 �Ų�*	
-6185557972203392769	wxid_pv9it79ze5ci22	2	1461647284	20160426	0	3	8	0	0	0000012261186101506158847	"
12261186101506158847wxid_pv9it79ze5ci22"	���ɿ����wxid_pv9it79ze5ci22铁哥 ����*	
-6186428438014250751	wxid_pv9it79ze5ci22	2	1461543516	20160425	0	3	8	0	0	0000012260315635695300865	"
12260315635695300865wxid_pv9it79ze5ci22"	����ْ̓�wxid_pv9it79ze5ci22铁哥 ����*	
-6199256869578067670	wxid_pv9it79ze5ci22	2	1460014248	20160407	0	3	8	0	0	0000012247487204131483946	"
12247487204131483946wxid_pv9it79ze5ci22"	�☋�����wxid_pv9it79ze5ci22铁哥 ����*	
-6216537076999311105	wxid_pv9it79ze5ci22	2	1457954287	20160314	0	3	8	0	0	0000012230206996710240511	"
12230206996710240511wxid_pv9it79ze5ci22"	�ᤃ���ݩwxid_pv9it79ze5ci22铁哥 ﻚ�*	
-6216538245844553453	wxid_pv9it79ze5ci22	2	1457954147	20160314	0	3	8	0	0	0000012230205827864998163	"
12230205827864998163wxid_pv9it79ze5ci22"	�������ݩwxid_pv9it79ze5ci22铁哥 㺚�*

**Comment by zhang-minchao** [comment]
模拟器失败
真机成功了
