### ISSUE TITLE
有人抄代码商用？

### ISSUE THREAD

**Issue by MichaelMai2000** [Chion82/WeChatMomentStat-Android#38]
http://f.hayoou.com/blogs/entry/%E5%93%88%E5%8F%8B%E7%A7%81%E5%AF%86%E5%A5%BD%E5%8F%8B%E5%8A%A9%E6%89%8B-%E4%B8%AA%E4%BA%BA%E7%89%88
https://github.com/jiubadao/hayoou-wechat-export
虽然加了一个wxpc解密，但是。。。感觉不大对劲
https://github.com/Chion82/WeChatMomentStat-Android/issues/16#issuecomment-328787400

**Comment by MewX** [comment]
GPL 3.0商用没问题，就是不符合开源社区价值观
