### ISSUE TITLE
如何定位到调用解码的方法?

### ISSUE THREAD

**Issue by gccdChen** [Chion82/WeChatMomentStat-Android#6]
我自己本来的手机没root,另一台已root的手机上,但是这里是拿到本地的数据,我能找到人朋友圈获取数据~插入到数据库的方法吗?

**Comment by gccdChen** [comment]
不然只能手工了..

**Comment by Chion82** [comment]
相关的类和方法在我的博客中有说明，可以参考下

**Comment by gunC** [comment]
怎么定位到这些方法的?我想定位下从网络获取朋友圈数据的方法

**Comment by gccdChen** [comment]
奥,你也是 逆向 慢慢找到对应的方法啊..辛苦哈..
[传送门](https://blog.chionlab.moe/2016/03/31/WeChatMomentStat-update-log/)
