### ISSUE TITLE
获取微信ID有的出现像是加密过的ID

### ISSUE THREAD

**Issue by ELYApp** [Chion82/WeChatMomentStat-Android#7]
hello，你好
在运行这个Demo的时候，发现抓取的微信数据，微信ID有的可以正常抓取显示正常，有的抓取回来的在数据库中显示wxid_XXXXXXXXX打头的一串字符串存储在数据库的userName一栏，这个是怎么回事？
怎么样才能正确获取到正常的微信ID号呢？
谢谢！

**Comment by Chion82** [comment]
wxid_XXXXX是用户的唯一uid，表明该用户还没有绑定微信ID，或者微信ID还没缓存到本地数据库中
